package SourceCode;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author sajja
 */
public class SearchForm extends javax.swing.JFrame {

    Connection c;
    Statement s;
    PreparedStatement pst;
    
    public SearchForm() {
        initComponents();
        
        ImageIcon frameIcon = new ImageIcon("src/images/appIcon.png");
        this.setIconImage(frameIcon.getImage());
        
        try {
            c = DriverManager.getConnection("jdbc:mysql:///oopdata", "root", "12345");
            s = c.createStatement();
        } catch(Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tempField = new javax.swing.JTextField();
        soilField = new javax.swing.JTextField();
        phField = new javax.swing.JTextField();
        cropField = new javax.swing.JTextField();
        rainField = new javax.swing.JTextField();
        sunField = new javax.swing.JTextField();
        periodField = new javax.swing.JTextField();
        infoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel2.setBackground(new java.awt.Color(225, 255, 253));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 24, -1, -1));

        searchField.setFont(searchField.getFont().deriveFont(searchField.getFont().getSize()+1f));
        jPanel2.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 22, 330, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Crop's Name :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Suitable pH rate for the soil :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Suitable soil type :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 178, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Temperature of the environment (°C) :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 222, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Required rainfall (mm) :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 266, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Required sunlight duration (h/day) :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Approximate growth period :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 354, -1, -1));

        tempField.setFont(tempField.getFont().deriveFont(tempField.getFont().getSize()+2f));
        tempField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempFieldActionPerformed(evt);
            }
        });
        jPanel2.add(tempField, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 219, 290, -1));

        soilField.setFont(soilField.getFont().deriveFont(soilField.getFont().getSize()+2f));
        jPanel2.add(soilField, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 175, 290, -1));

        phField.setFont(phField.getFont().deriveFont(phField.getFont().getSize()+2f));
        jPanel2.add(phField, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 131, 290, -1));

        cropField.setFont(cropField.getFont().deriveFont(cropField.getFont().getSize()+2f));
        jPanel2.add(cropField, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 87, 290, -1));

        rainField.setFont(rainField.getFont().deriveFont(rainField.getFont().getSize()+2f));
        rainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rainFieldActionPerformed(evt);
            }
        });
        jPanel2.add(rainField, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 263, 290, -1));

        sunField.setFont(sunField.getFont().deriveFont(sunField.getFont().getSize()+2f));
        sunField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunFieldActionPerformed(evt);
            }
        });
        jPanel2.add(sunField, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 307, 290, -1));

        periodField.setFont(periodField.getFont().deriveFont(periodField.getFont().getSize()+2f));
        periodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodFieldActionPerformed(evt);
            }
        });
        jPanel2.add(periodField, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 351, 290, -1));

        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N
        infoBtn.setText("More info");
        infoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(infoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 24, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tempFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempFieldActionPerformed

    private void rainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rainFieldActionPerformed

    private void sunFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunFieldActionPerformed

    private void periodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodFieldActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        try {
            pst = c.prepareStatement("select * from agridata where crope_name = ?");
            String cropName = searchField.getText();
            pst.setString(1, cropName);
            ResultSet rs = pst.executeQuery();
            if(rs.next() == true) {
                cropField.setText(rs.getString("crope_name"));
                phField.setText(rs.getString("soil_ph"));
                soilField.setText(rs.getString("soil_type"));
                tempField.setText(rs.getString("temp"));
                rainField.setText(rs.getString("rainfall"));
                sunField.setText(rs.getString("sunlight"));
                periodField.setText(rs.getString("period"));
            } else {
                ImageIcon icon = new ImageIcon("src/images/notFound.png");
                JOptionPane.showMessageDialog(null, "Crop's name is invalid !", "Sorry ☹️", JOptionPane.INFORMATION_MESSAGE,icon);
                cropField.setText("");
                phField.setText("");
                soilField.setText("");
                tempField.setText("");
                rainField.setText("");
                sunField.setText("");
                periodField.setText("");
                searchField.requestFocus();
            }
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        // TODO add your handling code here:
        try {
            String s = cropField.getText();
            if (!s.equals("")) {
                PrintForm printform = new PrintForm();
                printform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                printform.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Please, enter a Crop name.", "Invalid", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_infoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cropField;
    private javax.swing.JButton infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField periodField;
    private javax.swing.JTextField phField;
    private javax.swing.JTextField rainField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField soilField;
    private javax.swing.JTextField sunField;
    private javax.swing.JTextField tempField;
    // End of variables declaration//GEN-END:variables
}
